name: Release
on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit hash to release'
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.commit }}
    - name: Release steps
      # 其他发布步骤